// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

// import buttonCircle from "./button-circle"
// application.register("button-circle", buttonCircle)
